# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

reactNativePath = "../node_modules/react-native"

target 'IOSWithRN' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for IOSWithRN
  pod 'React', :path => "#{reactNativePath}", :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    # Add any other subspecs you want to use in your project
  ]

  pod 'yoga', :path => "#{reactNativePath}/ReactCommon/yoga"

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => "#{reactNativePath}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{reactNativePath}/third-party-podspecs/glog.podspec"
  pod 'Folly', :podspec => "#{reactNativePath}/third-party-podspecs/Folly.podspec"

end


